apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  imagePullSecrets:
    - name: harbor-auth
  securityContext:
    runAsUser: 0       # Pod çº§ root
    fsGroup: 0
  restartPolicy: Never
  containers:
    - name: jnlp
      image: gtharbor.legoutech.cn/library/jnlp-agent:v3
      imagePullPolicy: Always
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: http://192.168.100.50:8080
      securityContext:
        runAsUser: 0  
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
      - name: workspace
        mountPath: /home/jenkins/agent
      - name: docker-config
        mountPath: /kaniko/.docker
        
  volumes:
    - name: workspace
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: harbor-auth
