apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0       # Pod 级 root
    fsGroup: 0
  restartPolicy: Never
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: http://192.168.100.50:8080
      securityContext:
        runAsUser: 0  
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: dockerbin
          mountPath: /usr/bin/docker

    - name: go
      image: golang:1.24.4
      command:
        - cat
      tty: true
      workingDir: /home/jenkins/agent # 建议统一工作目录
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent
  volumes:
    - name: workspace
      emptyDir: {}
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: dockerbin 
      hostPath: 
        path: /usr/bin/docker 