apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins
  restartPolicy: Never

  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      env:
        - name: JENKINS_URL
          value: http://192.168.100.50:8080
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

    - name: go
      image: golang:1.24.4
      command:
        - cat
      tty: true
      workingDir: /home/jenkins/agent/workspace
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent

  volumes:
    - name: workspace
      hostPath:
        path: /home/gaotao/jenkins-workspace
        type: DirectoryOrCreate
